build:
    script:
        - apt-get -yqq update
        - apt-get -y install build-essential libboost-all
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - make
